---
- name: Configure My CLI Environment
  hosts: localhost
  connection: local
  become: yes

  vars:
    # --- Customized list of CLI tools ---
    # We define separate lists because package names can differ.
    # For example, 'bat' on Fedora is 'batcat' on older Debian/Ubuntu.
    redhat_packages:
      - git
      - curl
      - htop
      - fzf
      - bat        # Package is 'bat' on Fedora/RHEL
      - ripgrep
      - fd-find
      - zoxide

    debian_packages:
      - git
      - curl
      - htop
      - fzf
      - bat     # Package is 'batcat' on Debian/Ubuntu
      - ripgrep
      - fd-find
      - zoxide

  tasks:
    - name: Install common CLI tools (for Debian-based systems)
      ansible.builtin.apt:
        name: "{{ debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags:
        - packages

    - name: Install common CLI tools (for RedHat-based systems)
      ansible.builtin.dnf:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == "RedHat"
      tags:
        - packages
    
    # This task is a nice-to-have to make 'batcat' callable with 'bat'
    - name: Create a symlink for batcat to be called as bat (on Debian)
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
        force: yes # Overwrite if a different file is there
      when: ansible_os_family == "Debian"
      tags:
        - packages

    - name: Install oh-my-posh
      ansible.builtin.shell:
        cmd: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin
        creates: /usr/local/bin/oh-my-posh # This makes the task idempotent
      tags:
        - packages

    - name: Ensure .bashrc sources the .bashextension file
      become: no # This task runs as the user
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: '[ -f ~/.leonardo/.bashextension ] && source ~/.leonardo/.bashextension'
        state: present
        create: yes
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0644'
      tags:
        - dotfiles
