---
- name: Configure My CLI Environment
  hosts: localhost
  connection: local
  become: yes

  vars:
    # --- Customized list of CLI tools ---

    # Use a conditional to set the correct package name for bat
    bat_package_name: "{{ 'batcat' if ansible_distribution == 'Ubuntu' else 'bat' }}"

    redhat_packages:
      - git
      - curl
      - htop
      - fzf
      - bat
      - ripgrep
      - fd-find
      - zoxide
      - unzip

    debian_packages:
      - git
      - curl
      - htop
      - fzf
      - "{{ bat_package_name }}" # Use the dynamically set variable here
      - ripgrep
      - fd-find
      - zoxide
      - unzip

  tasks:
    - name: Install common CLI tools (for Debian-based systems)
      ansible.builtin.apt:
        name: "{{ debian_packages }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags:
        - packages

    - name: Install common CLI tools (for RedHat-based systems)
      ansible.builtin.dnf:
        name: "{{ redhat_packages }}"
        state: present
      when: ansible_os_family == "RedHat"
      tags:
        - packages

    # This task now specifically targets Ubuntu, where the symlink is needed.
    - name: Create a symlink for batcat to be called as bat (on Ubuntu)
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: /usr/local/bin/bat
        state: link
        force: yes
      when: ansible_distribution == 'Ubuntu' # More specific check
      tags:
        - packages

    - name: Install oh-my-posh
      ansible.builtin.shell:
        cmd: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin
        creates: /usr/local/bin/oh-my-posh
      tags:
        - packages

    # This block handles user-specific dotfile configurations
    - name: Configure user's dotfiles
      become: no
      tags:
        - dotfiles
      block:
        - name: Ensure .bashrc sources the .bashextension file
          ansible.builtin.lineinfile:
            # CORRECTED: Use a lookup to get the HOME env var at task execution time.
            # This respects 'become: no' and gets the correct user's home directory.
            path: "{{ lookup('env', 'HOME') }}/.bashrc"
            line: '[ -f ~/.leonardo/.bashextension ] && source ~/.leonardo/.bashextension'
            state: present
            create: yes
            mode: '0644'


