---
- name: Configure My CLI Environment
  hosts: localhost
  connection: local
  become: yes

  vars:
    # --- Your customized list of CLI tools ---
    cli_tools:
      - git
      - curl
      - htop
      - fzf
      - bat
      - ripgrep
      - fd-find  # Provides the 'fdfind' command
      - zoxide

  tasks:
    - name: Update apt cache and install common CLI tools
      ansible.builtin.apt:
        name: "{{ cli_tools }}"
        state: present
        update_cache: yes
      tags:
        - packages

    - name: Install oh-my-posh
      ansible.builtin.shell:
        cmd: curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin
        creates: /usr/local/bin/oh-my-posh # This makes the task idempotent
      tags:
        - packages

    - name: Copy .bashextension file to the user's home directory
      become: no # This task runs as the user, not root
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/.bashextension"
        dest: "{{ lookup('env', 'HOME') }}/.bashextension"
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0644'
      tags:
        - dotfiles

    - name: Ensure .bashrc sources the .bashextension file
      become: no # This task also runs as the user
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: '[ -f ~/.bashextension ] && source ~/.bashextension'
        state: present
        create: yes
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
        mode: '0644'
      tags:
        - dotfiles

